name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]

    steps:
     - name: Checkout code
        uses: actions/checkout@v2

      # Add debugging step to print contents of the build/release/linux directory
      - name: Debug output
        run: |
          echo "Listing contents of build/release directory:"
          ls -R ./build/release

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          node-version: 20

      - name: Run build script
        shell: pwsh
        run: .\build.ps1

      - name: Create release artifact
        uses: actions/upload-artifact@v2
        with:
          name: port_ninja_${{ matrix.goos }}_${{ matrix.goarch }}
          path: port_ninja_${{ matrix.goos }}_${{ matrix.goarch }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: port_ninja_linux_amd64
          path: ./build/release/linux

      - name: Download macOS binaries
        uses: actions/download-artifact@v2
        with:
          name: port_ninja_darwin_amd64
          path: ./build/release/darwin

      - name: Download Windows binaries
        uses: actions/download-artifact@v2
        with:
          name: port_ninja_windows_amd64.exe
          path: ./build/release/windows

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes for ${{ github.ref }}
            # Add release notes here
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ./build/release/linux/port_ninja_linux_amd64
            ./build/release/darwin/port_ninja_darwin_amd64
            ./build/release/windows/port_ninja_windows_amd64.exe
          asset_name: |
            port_ninja_linux_amd64
            port_ninja_darwin_amd64
            port_ninja_windows_amd64.exe
          asset_content_type: application/octet-stream
